# Generated by Django 2.1.7 on 2019-03-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='created_at',
            new_name='date',
        ),
    ]
